# Generated by Django 4.2.9 on 2024-01-27 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_apikey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="thumbnail",
            new_name="thumbnail_url",
        ),
    ]
