# Generated by Django 4.2.9 on 2024-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["title", "description"], name="title_description_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["title"], name="title_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["description"], name="description_idx"),
        ),
    ]
